try{code here
}

catch (exception_type_here variable_name_here) {code here}